### ISSUE TITLE
ZKM null pointer exception on flow obfuscation removal

### ISSUE THREAD

**Issue by barrN** [GraxCode/threadtear#37]
**Describe what's not working**
Running the ZKM deobfuscation tool, specifically "Flow obfuscation removal (ZKM)" results in a null pointer exception.
- running latest version 3.0.0
- as administrator, with -noverify
- notice it only crashes in some cases, not always able to recreate

**Java archive**
Link to archive: https://easyupload.io/dbiftd
- includes latest ZKM 14 obfuscation across the board

**Log / Screenshots**

```
Exception in thread "Execution-Thread" java.lang.NullPointerException
        at me.nov.threadtear.execution.zkm.FlowObfuscationZKM.removeZKMJumps(FlowObfuscationZKM.java:39)
        at java.util.ArrayList.forEach(Unknown Source)
        at me.nov.threadtear.execution.zkm.FlowObfuscationZKM.lambda$execute$2(FlowObfuscationZKM.java:32)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at me.nov.threadtear.execution.zkm.FlowObfuscationZKM.execute(FlowObfuscationZKM.java:32)
        at me.nov.threadtear.ThreadtearCore.lambda$run$5(ThreadtearCore.java:62)
        at java.util.ArrayList.forEach(Unknown Source)
        at me.nov.threadtear.ThreadtearCore.run(ThreadtearCore.java:59)
        at me.nov.threadtear.Threadtear.lambda$run$5(Threadtear.java:157)
        at java.lang.Thread.run(Unknown Source)
```

**Please complete the following information:**
Running on latest JDK, 14.

**Comment by GraxCode** [comment]
Did you use another task before? Seems like "null" ended up in the instruction list...

**Comment by barrN** [comment]
It was a fresh workspace with a fresh jar (linked one). I didn't run anything before.
