### ISSUE TITLE
Error loading jars into program

### ISSUE THREAD

**Issue by NginxTech** [GraxCode/threadtear#44]
I was trying to load a jar into ThreadTear, when I came across this error numerous amount of times across multiple jar files.

```Failed to load class  (java.lang.ArrayIndexOutOfBoundsException: 65448)`
java.lang.ArrayIndexOutOfBoundsException: 65528
        at org.objectweb.asm.ClassReader.readStringish(ClassReader.java:3691)
        at org.objectweb.asm.ClassReader.readClass(ClassReader.java:3706)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:486)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:394)
        at me.nov.threadtear.io.Conversion.toNode(Conversion.java:38)
        at me.nov.threadtear.io.JarIO.readEntry(JarIO.java:34)
        at me.nov.threadtear.io.JarIO.lambda$loadClasses$0(JarIO.java:23)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at me.nov.threadtear.io.JarIO.loadClasses(JarIO.java:23)
        at me.nov.threadtear.swing.tree.ClassTreePanel.loadFile(ClassTreePanel.java:213)
        at me.nov.threadtear.swing.tree.ClassTreePanel.lambda$onFileDrop$8(ClassTreePanel.java:194)
        at me.nov.threadtear.swing.panel.StatusBar$2.doInBackground(StatusBar.java:103)
        at me.nov.threadtear.swing.panel.StatusBar$2.doInBackground(StatusBar.java:100)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Failed to load class  (java.lang.ArrayIndexOutOfBoundsException: 65528)```

**Comment by NginxTech** [comment]
Attached is my thread-tear log file.
[threadtear.log](https://github.com/GraxCode/threadtear/files/5314420/threadtear.log)

**Comment by GraxCode** [comment]
Jar file was probably obfuscated with illegal constant pool entries that crash ASM.

**Comment by GraxCode** [comment]
If this is BinSecure @Col-E probably has a patch for you.

**Comment by NginxTech** [comment]
What is BinSecure?
