### ISSUE TITLE
Look and feel settings - IntelliJ Theme

### ISSUE THREAD

**Issue by RealFantaCoke** [GraxCode/threadtear#46]
**Describe what's not working**
Ich habe in den "Look and feel settings" das Theme auf IntelliJ gesetzt und dies hat scheinbar das gesamte Design zerhauen.
Das Design erscheint mir simpel unvollständig / nicht fertig.

**Java archive**
I don't get this one, sorry

**Log / Screenshots**
![image](https://user-images.githubusercontent.com/27063009/95688273-4b26b900-0c09-11eb-82b6-d64d1a1fda98.png)

**Please complete the following information:**
 - OS: Windows 10 Pro 2004 (x64)
 - Java version: Java 8
 - threadtear version: 3.0.0

**Additional context**

**Comment by GraxCode** [comment]
Looks like a darklaf bug to me, what do you think @weisJ ?

**Comment by weisJ** [comment]
Is this reproducible? If yes the log would be interesting. I guess somewhere during the LaF installation an exception was thrown preventing subsequent components to be reloaded.

**Comment by GraxCode** [comment]
Happens for me too.
```java
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.github.weisj.darklaf.ui.scrollpane.DarkScrollPaneUI.getViewportView(DarkScrollPaneUI.java:100)
	at com.github.weisj.darklaf.ui.scrollpane.DarkScrollPaneUI.getViewBackground(DarkScrollPaneUI.java:95)
	at com.github.weisj.darklaf.ui.scrollpane.DarkScrollPaneUI.updateScrollBarBackground(DarkScrollPaneUI.java:161)
	at com.github.weisj.darklaf.ui.scrollpane.DarkScrollPaneUI.lambda$createViewPropertyChangeListener$3(DarkScrollPaneUI.java:123)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8428)
	at java.awt.Component.setBackground(Component.java:1835)
	at javax.swing.JComponent.setBackground(JComponent.java:2733)
	at javax.swing.plaf.basic.BasicTreeUI.installDefaults(BasicTreeUI.java:697)
	at com.github.weisj.darklaf.ui.tree.DarkTreeUI.installDefaults(DarkTreeUI.java:124)
	at javax.swing.plaf.basic.BasicTreeUI.installUI(BasicTreeUI.java:644)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JTree.setUI(JTree.java:700)
	at javax.swing.JTree.updateUI(JTree.java:716)
	at me.nov.threadtear.swing.tree.JTreeWithHint.updateUI(JTreeWithHint.java:28)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1233)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1224)
	at com.github.weisj.darklaf.LafManager.updateLafRecursively(LafManager.java:460)
	at com.github.weisj.darklaf.LafManager.updateLaf(LafManager.java:452)
	at com.github.weisj.darklaf.LafManager.install(LafManager.java:438)
	at com.github.weisj.darklaf.LafManager.installTheme(LafManager.java:416)
	at com.github.weisj.darklaf.settings.ThemeSettings.lambda$applyTheme$7(ThemeSettings.java:468)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by weisJ** [comment]
Thank you! Could you check if the issue is fixed? (`--refresh-dependencies` flag in gradle might be necessary).

**Comment by MrExplode** [comment]
In general every look and feel change causes this stack trace for me.

**Comment by weisJ** [comment]
@MrExplode are you building the application yourself locally? If not you might want to try exactly that.

**Comment by GraxCode** [comment]
Works now.
