### ISSUE TITLE
Cannot open jar because svg failed to load

### ISSUE THREAD

**Issue by lz233** [GraxCode/threadtear#64]
**Describe what's not working**
Can not open jar because svg failed to load.

**Log / Screenshots**
```
Exception in thread "main" java.lang.RuntimeException: Exception while painting 'jar:file:/Users/lz233/Documents/xxx/threadtear-gui-3.0.1-all.jar!/me/nov/threadtear/threadtear.svg'.
	at com.github.weisj.darklaf.icons.DarkSVGIcon.createImage(DarkSVGIcon.java:177)
	at com.github.weisj.darklaf.icons.ImageSource.createImage(ImageSource.java:31)
	at com.github.weisj.darklaf.icons.IconUtil.createScaledImage(IconUtil.java:95)
	at com.github.weisj.darklaf.icons.IconUtil.iconToImage(IconUtil.java:87)
	at com.github.weisj.darklaf.icons.IconUtil.createScaledFrameIcon(IconUtil.java:75)
	at com.github.weisj.darklaf.icons.IconUtil.createFrameIcon(IconUtil.java:61)
	at com.github.weisj.darklaf.icons.IconLoader.createFrameIcon(IconLoader.java:383)
	at me.nov.threadtear.swing.SwingUtils.iconToFrameImage(SwingUtils.java:172)
	at me.nov.threadtear.Threadtear.<init>(Threadtear.java:36)
	at me.nov.threadtear.Threadtear.getInstance(Threadtear.java:44)
	at me.nov.threadtear.Threadtear.main(Threadtear.java:54)
Caused by: java.lang.RuntimeException: com.kitfox.svg.SVGException: java.lang.IllegalArgumentException: User must specify at least 2 colors
	at com.kitfox.svg.app.beans.SVGIcon.paintIcon(SVGIcon.java:326)
	at com.kitfox.svg.app.beans.SVGIcon.paintIcon(SVGIcon.java:213)
	at com.kitfox.svg.app.beans.SVGIcon.getImage(SVGIcon.java:113)
	at com.github.weisj.darklaf.icons.DarkSVGIcon.createImage(DarkSVGIcon.java:165)
	... 10 more
Caused by: com.kitfox.svg.SVGException: java.lang.IllegalArgumentException: User must specify at least 2 colors
	at com.kitfox.svg.ShapeElement.renderShape(ShapeElement.java:169)
	at com.kitfox.svg.Path.render(Path.java:94)
	at com.kitfox.svg.Group.render(Group.java:205)
	at com.kitfox.svg.Group.render(Group.java:205)
	at com.kitfox.svg.SVGRoot.render(SVGRoot.java:335)
	at com.kitfox.svg.SVGRoot.renderToViewport(SVGRoot.java:266)
	at com.kitfox.svg.SVGDiagram.render(SVGDiagram.java:111)
	at com.kitfox.svg.app.beans.SVGIcon.paintIcon(SVGIcon.java:322)
	... 13 more
Caused by: java.lang.IllegalArgumentException: User must specify at least 2 colors
	at java.desktop/java.awt.MultipleGradientPaint.<init>(MultipleGradientPaint.java:169)
	at java.desktop/java.awt.LinearGradientPaint.<init>(LinearGradientPaint.java:285)
	at com.kitfox.svg.LinearGradient.getPaint(LinearGradient.java:157)
	at com.kitfox.svg.ShapeElement.renderShape(ShapeElement.java:167)
	... 20 more
```

**Please complete the following information:**
 - OS: macOS 11.2
 - Java version: 8

**Comment by weisJ** [comment]
Which version of threadtear are you using?

**Comment by lz233** [comment]
3.0.1

**Comment by weisJ** [comment]
An immediate solution would be to build from source, as it uses a newer version of darlaf (which is used to load the svg icons). Otherwise it would probably be a good idea to upload a new release version containing the upstream fixes.
