### ISSUE TITLE
Can not run in Win 10 with JDK 19

### ISSUE THREAD

**Issue by hmirheydari** [GraxCode/threadtear#82]
When I ran the jar file I get:

C:\Users\Kevin\Downloads>java -jar threadtear-gui-3.0.1-all.jar
←[34m[2023-02-16 14:06:55]←[33m [INFO]←[0m←[30m Loaded darklaf-windows.dll.←[0m←[01m [at com.github.weisj.darklaf.platform.AbstractLibrary]←[2m←[0m
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field private static volatile java.nio.charset.Charset java.nio.charset.Charset.defaultCharset accessible: module java.base does not "opens java.nio.charset" to unnamed module @483f6d77
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
        at me.nov.threadtear.ThreadtearCore.configureEnvironment(ThreadtearCore.java:21)
        at me.nov.threadtear.Threadtear.main(Threadtear.java:51)

My Java information is as below:

C:\Users\Kevin\Downloads>java --version
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment Zulu19.32+15-CA (build 19.0.2+7)
OpenJDK 64-Bit Server VM Zulu19.32+15-CA (build 19.0.2+7, mixed mode, sharing)

My OS is Win 10 x64

**Comment by Wenaly** [comment]
yeah, please help me too

**Comment by ormaq** [comment]
I fixed this issue and made a pull request 
#83 

This repo seems to be a little inactive so until then attached is a java 18 compatible version 
[threadtear-gui-3.0.1-all.zip](https://github.com/GraxCode/threadtear/files/11300091/threadtear-gui-3.0.1-all.zip)

**Comment by Wenaly** [comment]
Thanks a lot!

**Comment by minhquan202** [comment]
bro, how  edit config to run with jdk 23
